image: python:3.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install -r requirements-test.txt
          - flake8 ./pydaikin/
          - black ./pydaikin/
          - pytest ./tests/
